### ISSUE TITLE
Nothing to make: no enabled makers

### ISSUE THREAD

**Issue by lpan** [jaawerth/nrun.vim#2] opened 2016-08-06 14:48 UTC
[Here](https://github.com/lpan/dotfiles/blob/master/files/desktop/init.vim#L74) is my setup. I really can't figure out what is wrong with it.

Thanks a lot

**Comment by lpan** [comment] 2016-08-06 14:56
`sudo npm i -g eslint` fixed it. It seems to be a neomake bug. I will close this for now :stuck_out_tongue:

**Comment by jaawerth** [comment] 2016-08-18 21:30
@lpan Sorry for the delay, I was a bit slower responding to it since it was already closed by the time I got to it. Looking now, I think this is actually my fault for writing incorrect/incomplete instructions in the Neomake example in the README.

The problem is that you're only setting `b:neomake_javascript_eslint_exe` when your vimrc is initially sourced, rather than each time you switch to that buffer - which means it won't work if you open vim with one file, then switch to another.

You could use `g:neomake_javascript_eslint_exe` instead to set it globally, but that would only work if you're only ever using a single open instance of (neo)vim with a single project.

A better approach would be to use an ftplugin (just put a file with `let b:neomake_javascript_eslint_exe = nrun#Which('eslint')` in `~/.config/nvim/ftplugin/javascript.vim` or `~/.vim/ftplugin/javascript.vim`) so it's automatically sourced when you switch to JS files, or you can set it with an autocommand, making sure it's run before `Neomake` is invoked.

Anyway, thanks for pointing this out, I'll update the README accordingly later today ;-)

**Comment by jaawerth** [comment] 2016-08-18 22:11
Oh, and to do it with an autoload command you can do something like this in your `init.vim`/`.vimrc` (which I'm about to add to the README):

``` vim
let g:neomake_javascript_enabled_makers = ['eslint']` 
au BufEnter *.js let b:neomake_javascript_eslint_exe = nrun#Which('eslint')
```

You can set the enabled makers globally, like, so, OR you can change the "go" to "b" and set it on the buffer level as part of the autocmd if you wanted to be able to set it differently for different file locations/projects.

**Closed as completed** 2016-08-18 22:25 UTC

**Comment by lpan** [comment] 2016-08-19 01:19
@jaawerth thanks a lot man! :+1:
